### ISSUE TITLE
Unable to download stackskills courses 

### ISSUE THREAD

**Issue by jzastoupil** [barakagb/gb-dl#1]
I finally got the script to work on my Ubuntu  machine but keep getting this:
Trying to Login ...
[+]Login successful.
Collecting course information ...
Course not found or You need to purchase course.

I absolutely have access to the course url in question and am a relative Python newbie so I'm not entirely sure how to troubleshoot

**Comment by barakagb** [comment]
H

> I finally got the script to work on my Ubuntu machine but keep getting this:
> Trying to Login ...
> [+]Login successful.
> Collecting course information ...
> Course not found or You need to purchase course.
> 
> I absolutely have access to the course url in question and am a relative Python newbie so I'm not entirely sure how to troubleshoot

Hellow jzastoupil , could you please share the course url , and i will try to resolve the issue.

**Comment by barakagb** [comment]
This issue has been resolved ...Please reinstall gb-dl .Thanks

**Comment by jzastoupil** [comment]
Thank you, its working perfectly :)
