### ISSUE TITLE
not working - where to enter key?

### ISSUE THREAD

**Issue by broodfusion** [barakagb/gb-dl#11]
using python version 2.7
![image](https://user-images.githubusercontent.com/11618564/77104712-b4c74780-69d9-11ea-9462-89e4fbc672f4.png)

- Downloaded from pip
- don't know where to enter key
- doesn't ask for password
- see screenshot
![image](https://user-images.githubusercontent.com/11618564/77104533-674ada80-69d9-11ea-89f8-e4a3075e8a06.png)

**Comment by barakagb** [comment]
@broodfusion It works on python2 and python3  check screeenshot for python2.
Try updating your python or try python3.

Key will be requested later when downloading the course.

1.Try running gb-dl.py
2. update your python2 or try python3

Screenshot
![Screenshot from 2020-03-19 22-20-47](https://user-images.githubusercontent.com/30619781/77106328-f5ea4680-6a2f-11ea-9ec6-7b99517b243f.png)

**Comment by broodfusion** [comment]
ok installing python3.8 corrected this
Can you make a quick update to support https://learn.tylermcginnis.com/ ?
Thanks

**Comment by barakagb** [comment]
I think the issue was the OpenSSL needed to be updated. Am glad it worked am closing this issue.
