### ISSUE TITLE
[-] Error : [WinError 123] The filename, directory name, or volume label syntax is incorrect:

### ISSUE THREAD

**Issue by gohrobingo** [barakagb/gb-dl#14]
Hi, I encountered this error: [-] Error : [WinError 123] The filename, directory name, or volume label syntax is incorrect:

Reading from your last post, i guess it is some folder not being created. I proceeded to add the folder on my own. However, there is an issue as the folder name contains an invalid character.

Can you parse the title and remove any invalid characters before creating the folder?

Thanks

**Comment by barakagb** [comment]
Hi @gohrobingo , what gb-dl version and OS are you running ? also include a screenshot and the link to the course if possible .Thanks.

**Comment by gohrobingo** [comment]
I am running gb-dl version 1.6.3.2 and OS windows 10.

Attached is the screen shot: https://i.imgur.com/hdQVBPN.png

**Comment by barakagb** [comment]
upgrade gb-dl to version 1.6.3.3
pip install gb-dl -U

**Comment by gohrobingo** [comment]
Hi, i have updated and it still shows me the same error.

Screenshot: https://i.imgur.com/1yaTyvm.png

**Comment by barakagb** [comment]
Hi the issue is fixed upgrade to version 1.6.3.4 
pip install gb-dl -U
