### ISSUE TITLE
Doesn't Create Course Structure

### ISSUE THREAD

**Issue by gohrobingo** [barakagb/gb-dl#15]
Hi, I am using version 1.6.3.3. It doesn't create any course structure by means of folders system. In fact, it didn't create any folders and just downloaded it in the main folder for one of the courses.

Please make it more consistent  to always create folders and sub folders so that it is easier for us to manage.

Just another thing, some of the files are downloaded as .bin file, while some naming of the files are not accurate.

Thanks!

**Comment by barakagb** [comment]
hi @gohrobingo , The script downloads the course with its structure . As for the bin file just change it to mp4 and it should work , for the naming the names come from the course its self the script does not rename the files.
Kindly share the course link that did not download with the course structure.Thanks

**Comment by gohrobingo** [comment]
Previously, Python Fundamentals and Javascript Bible had problems using previous version. But now I am using the 1.6.3.4 version, everything looks good for now.

**Comment by barakagb** [comment]
Glad it works! .
