### ISSUE TITLE
[-] Error : [WinError 2] The system cannot find the file specified:

### ISSUE THREAD

**Issue by gohrobingo** [barakagb/gb-dl#16]
Hi, The previous issue of stripping invalid characters to create a folder has been settled. However, recursively, whether the course title has invalid characters, it will throw out the above error. Please help. Thanks.

**Comment by barakagb** [comment]
please  share the course link that produces the error and a screenshot of the output if you may.

**Comment by gohrobingo** [comment]
Hi, here's the course and screenshot. I have tried. Many courses with ":" in the title unfortunately can't work.

https://i.imgur.com/VrN4tZp.png

**Comment by barakagb** [comment]
Hi , you hid some info in the screen shot that i need to detect the problem and fix it kindly share the screen shot via email if you can so I can come up with a fix. Thanks

**Comment by barakagb** [comment]
I the meanwhile try to upgrade to v1.6.3.5

**Comment by gohrobingo** [comment]
Will try v1.6.3.5.

Do you need the path of where the files are saved?

**Comment by barakagb** [comment]
Yes but try upgrading to v1.6.3.6

**Comment by gohrobingo** [comment]
v1.6.3.6 can't even run. It just shows error:

                  / ____|  _ \               | | |
                 | |  __| |_) |  ______    __| | |
                 | | |_ |  _ <  |______|  / _` | |
                 | |__| | |_) |          | (_| | |
                  \_____|____/            \__,_|_|

                                        Version : 1.6.3.6
                            Author  : BarakaGB
                            Visit   : https://github.com/barakagb/gb-dl
                            Donation: https://www.buymeacoffee.com/barakagb
                            Key url : https://bmc.xyz/l/gbdl

    A python based utility to download courses from infosec4tc.teachable.com ,
    ehacking.net ,stackskills.com and designerup.co ...etc for personal offline
    use.



    Usage: gb-dl.py [-h]


Enter course url : https://stackskills.com/courses/enrolled/249565
Email : 
Password :
Trying to Login ...
Cloudflare reCaptcha detected, unfortunately you haven't loaded an anti reCaptcha provider correctly via the 'recaptcha' parameter.
Enter cookie instead: 
Downloading to :
Collecting course information ...
[-] Error : can only concatenate str (not "bytes") to str

**Comment by barakagb** [comment]
Try v1.6.3.7 , Please also share the screen shot in Private so I can further investigate it. Thanks

**Comment by gohrobingo** [comment]
Thanks. v1.6.3.7 is working well so far. You still need any screenshot?

**Comment by gohrobingo** [comment]
There is an issue with 1.6.3.7. It will skip a few sections without downloading.

Course url: https://stackskills.com/courses/enrolled/62225
Screenshot attached: https://i.imgur.com/lrZZiJA.png

**Comment by gohrobingo** [comment]
There are alot of bugs in v1.6.3.7. For this course, it keeps downloading the same files in different section.

Course URL: https://stackskills.com/courses/enrolled/67419
Screenshot:https://i.imgur.com/9UDfQfo.png

**Comment by barakagb** [comment]
Hi @gohrobingo  , that seems strange I don't think its a bug rather the course is in a different format from other course because the script would work for other many courses but this . I would need to access the course so I can figure out what is the issue otherwise I will just be a game of guessing.

Try upgrading to version 1.6.3.8 also if you can try downloading the courses in Linux preferably ubuntu . Thanks
