### ISSUE TITLE
Cloudflare Protection

### ISSUE THREAD

**Issue by PhusionDev** [barakagb/gb-dl#17]
No matter what I do I get this error. I've upgraded to Python 3.8.2 and openssl is current. I've tried typing in the entire cookie from the header and cookie auth fails as well.

Cloudflare reCaptcha detected, unfortunately you haven't loaded an anti reCaptcha provider correctly via the 'recaptcha' parameter.
Enter cookie instead:

**Comment by barakagb** [comment]
Hi , you are probably not entering the wrong cookie value. What what's the
cookie variable name you are using?

**Comment by PhusionDev** [comment]
Hello. when I refersh the page and look at the XHR headers for event -> Request Headers -> cookie:

**Comment by PhusionDev** [comment]
sorry, I found the correct value _session_id=

**Comment by barakagb** [comment]
That's great @PhusionDev  .
