### ISSUE TITLE
Problems Downloading Teachable Course

### ISSUE THREAD

**Issue by jzastoupil** [barakagb/gb-dl#19]
I have purchased the course but would like to download it for offline viewing.  
Course URL: https://practice.karindimitrovova.com/courses/enrolled/707539
I found the teachable login URL for the course and added it to your if statement
elif "karindimitrovova" in self.course_url:
                    login_url = "https://sso.teachable.com/secure/444933/users/sign_in?flow_school_id=444933"

I am grabbing the cookie from the session id in the first  listing here (I've also tried the one in the second to be sure)
![image](https://user-images.githubusercontent.com/48563919/82830883-8b64e500-9e7c-11ea-92be-fe13637bd952.png)
but I continue to get this:
![image](https://user-images.githubusercontent.com/48563919/82830903-9750a700-9e7c-11ea-8ed0-2c1f4f98f377.png)

I get no reCaptcha when logging in on Chrome but it keeps telling me reCaptcha has been detected :(

**Comment by tgreenev** [comment]
I was able to get this. I use chrome, and even though it has a bunch of cookies, you have to use **_session_id** and then it will worked. Just tried this. 

![image](https://user-images.githubusercontent.com/42524190/84388846-3c7cb680-abc3-11ea-8ccf-0f1bec4e53aa.png)

**Comment by tgreenev** [comment]
I will add that the downloads have been downloaded as bin files. However, I think I cna whip up a powershell script to rename them if they are all similar. If you remove the dash, random string and .bin, then it still plays.

**Comment by barakagb** [comment]
Hi @tgreenev , the bin files can be opened with some media player (e.g totem in ubuntu) with no problems. You can simply change the ext from bin to mp4 , in addition after the whole course is downloaded the script automatically changes the extensions to mp4 .

**Comment by tgreenev** [comment]
The script finished, and didn't not update the files name. No biggie, and I
just used powershell to remove it. I am on Windows by the way.

**Comment by barakagb** [comment]
what version of gb-dl are you using ?

**Comment by tgreenev** [comment]
1.6.4.2

**Comment by barakagb** [comment]
it should have automatically change ... i will look into it.Thanks
