### ISSUE TITLE
Videos downloading twice

### ISSUE THREAD

**Issue by baggot4** [barakagb/gb-dl#21]
When I'm downloading the course the videos download twice so it takes twice as long. One will be the name ex. Start.mp4 and the other will be start-hkjgakfjg.mp4

**Comment by baggot4** [comment]
downloading from here [https://codewithmosh.com/courses/enrolled/293204](url)

**Comment by barakagb** [comment]
Hi @baggot4 , could you provide the screenshot of the script running and the downloaded duplicate files.

**Comment by baggot4** [comment]
> Hi @baggot4 , could you provide the screenshot of the script running and the downloaded duplicate files.

https://gyazo.com/a654107b2fe78663db49227c9f952d5a
https://gyazo.com/907615ba6aaee4e16691257b7fda1cee

**Comment by baggot4** [comment]
the second version starts as a .bin file then after the whole course is finished it turns into a .mp4

**Comment by barakagb** [comment]
@baggot4 The issue is fixed .Kindly upgrade to v1.6.4.2 (pip install gb-dl -U).
Kindly consider supporting by donating if you haven't. Thanks
