### ISSUE TITLE
ModuleNotFoundError: No module named 'requests_toolbelt'

### ISSUE THREAD

**Issue by Planks** [barakagb/gb-dl#22]
Hi barakagb

I am hoping you can assist me with running this script

Here is my console log with the error on a clean install of python 3.8 and windows 10 64 bit

```
C:\Users\andre>pip install gb-dl
Collecting gb-dl
  Downloading gb-dl-1.6.4.5.tar.gz (6.8 kB)
Collecting requests
  Downloading requests-2.24.0-py2.py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 4.8 MB/s
Collecting unidecode
  Downloading Unidecode-1.1.1-py2.py3-none-any.whl (238 kB)
     |████████████████████████████████| 238 kB 6.4 MB/s
Collecting beautifulsoup4
  Downloading beautifulsoup4-4.9.1-py3-none-any.whl (115 kB)
     |████████████████████████████████| 115 kB 6.4 MB/s
Collecting youtube-dl
  Downloading youtube_dl-2020.6.16.1-py2.py3-none-any.whl (1.8 MB)
     |████████████████████████████████| 1.8 MB ...
Collecting lxml
  Downloading lxml-4.5.2-cp38-cp38-win_amd64.whl (3.5 MB)
     |████████████████████████████████| 3.5 MB ...
Collecting wget
  Downloading wget-3.2.zip (10 kB)
Collecting cfscraper
  Downloading cfscraper-0.11.tar.gz (7.8 kB)
Collecting chardet<4,>=3.0.2
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
     |████████████████████████████████| 133 kB 6.8 MB/s
Collecting idna<3,>=2.5
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB ...
Collecting certifi>=2017.4.17
  Downloading certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
     |████████████████████████████████| 156 kB ...
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Downloading urllib3-1.25.9-py2.py3-none-any.whl (126 kB)
     |████████████████████████████████| 126 kB 6.8 MB/s
Collecting soupsieve>1.2
  Downloading soupsieve-2.0.1-py3-none-any.whl (32 kB)
Using legacy setup.py install for gb-dl, since package 'wheel' is not installed.
Using legacy setup.py install for wget, since package 'wheel' is not installed.
Using legacy setup.py install for cfscraper, since package 'wheel' is not installed.
Installing collected packages: chardet, idna, certifi, urllib3, requests, unidecode, soupsieve, beautifulsoup4, youtube-dl, lxml, wget, cfscraper, gb-dl
    Running setup.py install for wget ... done
    Running setup.py install for cfscraper ... done
    Running setup.py install for gb-dl ... done
Successfully installed beautifulsoup4-4.9.1 certifi-2020.6.20 cfscraper-0.11 chardet-3.0.4 gb-dl-1.6.4.5 idna-2.10 lxml-4.5.2 requests-2.24.0 soupsieve-2.0.1 unidecode-1.1.1 urllib3-1.25.9 wget-3.2 youtube-dl-2020.6.16.1

C:\Users\andre>pip install wheel
Collecting wheel
  Downloading wheel-0.34.2-py2.py3-none-any.whl (26 kB)
Installing collected packages: wheel
Successfully installed wheel-0.34.2

C:\Users\andre>pip install gb-dl
Requirement already satisfied: gb-dl in c:\python38\lib\site-packages (1.6.4.5)
Requirement already satisfied: requests in c:\python38\lib\site-packages (from gb-dl) (2.24.0)
Requirement already satisfied: unidecode in c:\python38\lib\site-packages (from gb-dl) (1.1.1)
Requirement already satisfied: beautifulsoup4 in c:\python38\lib\site-packages (from gb-dl) (4.9.1)
Requirement already satisfied: youtube-dl in c:\python38\lib\site-packages (from gb-dl) (2020.6.16.1)
Requirement already satisfied: lxml in c:\python38\lib\site-packages (from gb-dl) (4.5.2)
Requirement already satisfied: wget in c:\python38\lib\site-packages (from gb-dl) (3.2)
Requirement already satisfied: cfscraper in c:\python38\lib\site-packages (from gb-dl) (0.11)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\python38\lib\site-packages (from requests->gb-dl) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\python38\lib\site-packages (from requests->gb-dl) (2020.6.20)
Requirement already satisfied: idna<3,>=2.5 in c:\python38\lib\site-packages (from requests->gb-dl) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\python38\lib\site-packages (from requests->gb-dl) (1.25.9)
Requirement already satisfied: soupsieve>1.2 in c:\python38\lib\site-packages (from beautifulsoup4->gb-dl) (2.0.1)

C:\Users\andre>
C:\Users\andre>gb-dl.py
Traceback (most recent call last):
  File "C:\Python38\Scripts\gb-dl.py", line 14, in <module>
    import cfscraper as scrape
  File "c:\python38\lib\site-packages\cfscraper\__init__.py", line 16, in <module>
    from requests_toolbelt.utils import dump
ModuleNotFoundError: No module named 'requests_toolbelt'

C:\Users\andre>
```

**Comment by barakagb** [comment]
Hi there, try pip install requests-toolbelt.Thanks

**Comment by Planks** [comment]
Installed ok

Now a different error

```
C:\Users\andre\Desktop\mems>C:\Python38\Scripts\gb-dl.py
Traceback (most recent call last):
  File "C:\Python38\Scripts\gb-dl.py", line 14, in <module>
    import cfscraper as scrape
  File "c:\python38\lib\site-packages\cfscraper\__init__.py", line 56, in <module>
    from .interpreters import JavaScriptInterpreter
ModuleNotFoundError: No module named 'cfscraper.interpreters'
```

**Comment by barakagb** [comment]
pip install cloudscraper

**Comment by Planks** [comment]
> C:\Users\andre\Desktop\mems>pip install cloudscraper
> Collecting cloudscraper
>   Downloading cloudscraper-1.2.42-py2.py3-none-any.whl (110 kB)
>      |████████████████████████████████| 110 kB 3.2 MB/s
> Collecting pyparsing>=2.4.7
>   Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
>      |████████████████████████████████| 67 kB ...
> Requirement already satisfied: requests-toolbelt>=0.9.1 in c:\python38\lib\site-packages (from cloudscraper) (0.9.1)
> Requirement already satisfied: requests>=2.9.2 in c:\python38\lib\site-packages (from cloudscraper) (2.24.0)
> Requirement already satisfied: idna<3,>=2.5 in c:\python38\lib\site-packages (from requests>=2.9.2->cloudscraper) (2.10)
> Requirement already satisfied: chardet<4,>=3.0.2 in c:\python38\lib\site-packages (from requests>=2.9.2->cloudscraper) (3.0.4)
> Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\python38\lib\site-packages (from requests>=2.9.2->cloudscraper) (1.25.9)
> Requirement already satisfied: certifi>=2017.4.17 in c:\python38\lib\site-packages (from requests>=2.9.2->cloudscraper) (2020.6.20)
> Installing collected packages: pyparsing, cloudscraper
> Successfully installed cloudscraper-1.2.42 pyparsing-2.4.7
> 
> C:\Users\andre\Desktop\mems>C:\Python38\Scripts\gb-dl.py
> Traceback (most recent call last):
>   File "C:\Python38\Scripts\gb-dl.py", line 14, in <module>
>     import cfscraper as scrape
>   File "c:\python38\lib\site-packages\cfscraper\__init__.py", line 56, in <module>
>     from .interpreters import JavaScriptInterpreter
> ModuleNotFoundError: No module named 'cfscraper.interpreters'
> 
> C:\Users\andre\Desktop\mems>pip install cfscraper
> Requirement already satisfied: cfscraper in c:\python38\lib\site-packages (0.11)
> 
> C:\Users\andre\Desktop\mems>C:\Python38\Scripts\gb-dl.py
> Traceback (most recent call last):
>   File "C:\Python38\Scripts\gb-dl.py", line 14, in <module>
>     import cfscraper as scrape
>   File "c:\python38\lib\site-packages\cfscraper\__init__.py", line 56, in <module>
>     from .interpreters import JavaScriptInterpreter
> ModuleNotFoundError: No module named 'cfscraper.interpreters'

**Comment by barakagb** [comment]
Mhh thats strange please trying using py 3.6 and reinstall gb-dl

**Comment by barakagb** [comment]
Hi @Planks  issues is  now fixed . Uninstall gb-dl and re-install it.

pip uninstall gb-dl then pip install gb-dl

**Comment by Planks** [comment]
Are you sure? Reinstalling pulls down the same version,  gb-dl 1.6.4.5, and it has the same error. I don't see any new commits to the repo in https://github.com/barakagb/gb-dl/commits/master

**Comment by barakagb** [comment]
Yes am sure ... Try it out

**Comment by barakagb** [comment]
Uninstall then reinstall.

**Comment by barakagb** [comment]
Hi @Planks any feedback ?
