### ISSUE TITLE
Error : list index out of range

### ISSUE THREAD

**Issue by hapkom2k** [barakagb/gb-dl#23]
Hello
Trying to download course via your  script, but got  Error : list index out of range

```
Trying cookie authentication ...
[+] Cookie authentication succeeded
Getting course sections ...
Downloading course image ...
[-] Error : list index out of range
```

**Comment by barakagb** [comment]
Hi , please share the url to the course you trying to dowload.

**Comment by hapkom2k** [comment]
https://codewithmosh.com/courses/enrolled/417695

**Comment by hapkom2k** [comment]
i also tryed course at https://academy.zerotomastery.io/courses/enrolled/694968, but got [-] Invalid course URL. error
thats strange, it uses teachable.com as a platform.

**Comment by barakagb** [comment]
Hi @hapkom2k  ,I have try upgrading the script using pip install gb-dl -U 

Here is my output

Course name : Complete Python Mastery
Trying cookie authentication ...
[+] Cookie authentication succeeded
Getting course sections ...
[-] Could not download course image.

[+] Found Section :  1- Getting Started (32m)

**Comment by barakagb** [comment]
> i also tryed course at https://academy.zerotomastery.io/courses/enrolled/694968, but got [-] Invalid course URL. error
> thats strange, it uses teachable.com as a platform.

The script was not designed for this . However after upgrading the script you may test if it works.

**Comment by hapkom2k** [comment]
Unfortunately, it doesn't work

```
E:\CodeMosh>gb-dl


                   _____ ____                 _ _
                  / ____|  _ \               | | |
                 | |  __| |_) |  ______    __| | |
                 | | |_ |  _ <  |______|  / _` | |
                 | |__| | |_) |          | (_| | |
                  \_____|____/            \__,_|_|

                                        Version : v1.6.4.6
                            Author  : BarakaGB
                            Visit   : https://github.com/barakagb/gb-dl
                            Donation: https://www.buymeacoffee.com/barakagb
                            Key url : https://bmc.xyz/l/gbdl

    A python based utility to download courses from infosec4tc.teachable.com ,
    ehacking.net ,stackskills.com and designerup.co ...etc for personal offline
    use.


    Usage: gb-dl.py [-h]

Enter course url : https://codewithmosh.com/courses/enrolled/417695
Email : 
Password :
Trying to Login ...
Cloudflare reCaptcha detected
Enter cookie instead: 
Downloading to :E:\CodeMosh
Collecting course information ...

Course name : Complete Python Mastery
Trying cookie authentication ...
[+] Cookie authentication succeeded
Getting course sections ...
Downloading course image ...
[-] Could not download course image.
[-] Error : list index out of range
```

**Comment by barakagb** [comment]
try running gb-dl with -i and share the output

**Comment by hapkom2k** [comment]
outpu is same

**Comment by barakagb** [comment]
Can you contact me  via email ?

**Comment by hapkom2k** [comment]
yea, what is email address?

**Comment by hapkom2k** [comment]
The problem turned out to be in the connection, when using a VPN the error does not pop up. But another one appears. It's a shame, but the script did not work for me.
