### ISSUE TITLE
import gb-dl "invalid syntax" (Windows)

### ISSUE THREAD

**Issue by joe4n** [barakagb/gb-dl#24]
Using Windows command prompt (Win 10 x64, Python 3.8.5, Pip 20.2.1):

```
>> C:\Windows\system32>python "C:\Users\xxx\Downloads\gb-dl.py"
  File "C:\Users\xxx\Downloads\gb-dl.py", line 1
    import gb-dl
             ^
SyntaxError: invalid syntax
```
gb-dl is installed, however: 
```
>> C:\Windows\system32>python -m pip install gb-dl
Requirement already satisfied: gb-dl in c:\users\xxx\appdata\local\programs\python\python38-32\lib\site-packages (1.6.4.6)
Requirement already satisfied: requests in c:\users\xxx\appdata\local\programs\python\python38-32\lib\site-packages (from gb-dl) (2.24.0)
Requirement already satisfied: lxml in c:\users\xxx\appdata\local\programs\python\python38-32\lib\site-packages (from gb-dl) (4.5.2)
Requirement already satisfied: wget in c:\users\xxx\appdata\local\programs\python\python38-32\lib\site-packages (from gb-dl) (3.2)
Requirement already satisfied: unidecode in c:\users\xxx\appdata\local\programs\python\python38-32\lib\site-packages (from gb-dl) (1.1.1)
Requirement already satisfied: beautifulsoup4 in c:\users\xxx\appdata\local\programs\python\python38-32\lib\site-packages (from gb-dl) (4.9.1)
Requirement already satisfied: youtube-dl in c:\users\xxx\appdata\local\programs\python\python38-32\lib\site-packages (from gb-dl) (2020.7.28)
Requirement already satisfied: cfscraper in c:\users\xxx\appdata\local\programs\python\python38-32\lib\site-packages (from gb-dl) (0.14)
Requirement already satisfied: idna<3,>=2.5 in c:\users\xxx\appdata\local\programs\python\python38-32\lib\site-packages (from requests->gb-dl) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\xxx\appdata\local\programs\python\python38-32\lib\site-packages (from requests->gb-dl) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\xxx\appdata\local\programs\python\python38-32\lib\site-packages (from requests->gb-dl) (2020.6.20)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\xxx\appdata\local\programs\python\python38-32\lib\site-packages (from requests->gb-dl) (1.25.10)
Requirement already satisfied: soupsieve>1.2 in c:\users\xxx\appdata\local\programs\python\python38-32\lib\site-packages (from beautifulsoup4->gb-dl) (2.0.1)
Requirement already satisfied: pyparsing>=2.4.7 in c:\users\xxx\appdata\local\programs\python\python38-32\lib\site-packages (from cfscraper->gb-dl) (2.4.7)
Requirement already satisfied: requests-toolbelt>=0.9.1 in c:\users\xxx\appdata\local\programs\python\python38-32\lib\site-packages (from cfscraper->gb-dl) (0.9.1)
```
Any suggestions?  Thank you!

**Comment by joe4n** [comment]
I am able to execute gb-dl via the compiled python file located here, but this doesn't allow me to pass arguments to it:  

C:\Users\xxx\AppData\Local\Programs\Python\Python38-32\Scripts\__pycache__\gb-dl.cpython-38.pyc

**Comment by barakagb** [comment]
Hi @joe4n ,
 Have you installed gb-dl via pip ? also can you run the script ?

**Comment by barakagb** [comment]
> C:\Users\xxx\AppData\Local\Programs\Python\Python38-32\Scripts__pycache__\gb-dl.cpython-38.pyc

On windows you should try C:/path/to/script/python gb-dl.py -h check image below for reference.

<img width="543" alt="help" src="https://user-images.githubusercontent.com/30619781/89790353-79fdb180-db2a-11ea-8d32-ba7cbeb1a133.PNG">

**Comment by joe4n** [comment]
Hi @barakagb 

Yes, I installed gb-dl via pip - as illustrated in my original comment.  

I get the 'SyntaxError: invalid syntax' error when attempting to run the gd-dl.py script:
```
import gb-dl
gb-dl()
```
I've tried fixing this by manually adding folders where gb-dl has been installed to PYTHONPATH, but this doesn't make any difference.

**Comment by joe4n** [comment]
> also check out [https://stackoverflow.com/questions/2640971/windows-is-not-passing-command-line-arguments-to-python-programs-executed-from-t](url)

I will experiment with registry fixes.  Thank you!

**Comment by barakagb** [comment]
> 
> 
> Hi @barakagb
> 
> Yes, I installed gb-dl via pip - as illustrated in my original comment.
> 
> I get the 'SyntaxError: invalid syntax' error when attempting to run the gd-dl.py script:
> 
> ```
> import gb-dl
> gb-dl()
> ```
> 
> I've tried fixing this by manually adding folders where gb-dl has been installed to PYTHONPATH, but this doesn't make any difference.

You should run gb-dl via command line 
gb-dl.py or python gb-dl.py

**Comment by barakagb** [comment]
@joe4n  have you tried the above ?

**Comment by sail1369** [comment]
same issue, installed via conda env, all files are updated,

**Comment by sail1369** [comment]
> 
> 
> same issue, installed via conda env, all files are updated,

my bad, it worked when i typed gb-dl.py, it opened up in my editor and i ran it from there

**Comment by sail1369** [comment]
the site that i need: https://codingfaculty.com/courses/41987/ is not working

**Comment by barakagb** [comment]
@sail1369  I will try to look onto it.

**Comment by barakagb** [comment]
Hi @joe4n  I'm closing this issue due to no response from you.

@sail1369  For your concern kindly open an issue  for it if you want and will try and solve it there.

**Comment by barakagb** [comment]
@sail1369 kindly upgrade gb-dl i've added the site.

pip install gb-dl -U

**Comment by sail1369** [comment]
oh cool, thank you soo much!
