### ISSUE TITLE
I dont get any keys

### ISSUE THREAD

**Issue by Siddharth-Selvarajan** [barakagb/gb-dl#25]
I don't get keys

Then get your key here: https://bmc.xyz/l/gbdl 
N.B key will be sent to your email.

only instruction files received.

**Comment by barakagb** [comment]
Hi @Siddharth-Selvarajan  ,please check your email inbox and spam . The email linked to you PayPal account.Thanks

**Comment by Siddharth-Selvarajan** [comment]
fine i got it.

but, Installation error

![image](https://user-images.githubusercontent.com/69203685/90779440-77b20900-e31b-11ea-964f-a6767516cc6f.png)

**Comment by barakagb** [comment]
Try Pip install gb-dl

**Comment by Siddharth-Selvarajan** [comment]
tried. gb-dl installed. but same problem.

**Comment by barakagb** [comment]
Please share the screen shot

**Comment by Siddharth-Selvarajan** [comment]
![image](https://user-images.githubusercontent.com/69203685/90840342-639bf500-e377-11ea-908d-784c81afccb6.png)

**Comment by Siddharth-Selvarajan** [comment]
for windows

![image](https://user-images.githubusercontent.com/69203685/90842983-30109900-e37e-11ea-80a6-b3376804ff04.png)

**Comment by Siddharth-Selvarajan** [comment]
Now, Working for me. Create Virtual Env. Thank you so much.

**Comment by Amolkulkarni2** [comment]
Hi @Siddharth-Selvarajan :can you please guide me how to install it on windows?  my email id : amolkulkarni.2@gmail.com
