### ISSUE TITLE
infosec4tc session login error

### ISSUE THREAD

**Issue by Siddharth-Selvarajan** [barakagb/gb-dl#27]
![image](https://user-images.githubusercontent.com/69203685/91247823-ce32a380-e770-11ea-9ce7-582219fde829.png)

**Comment by barakagb** [comment]
Hi @Siddharth-Selvarajan  .
Issue is fixed kindly upgrade to v.1.6.5.3 
pip install gb-dl -U

Thanks

**Comment by Siddharth-Selvarajan** [comment]
thank you so much
