### ISSUE TITLE
zerotomastery error

### ISSUE THREAD

**Issue by Siddharth-Selvarajan** [barakagb/gb-dl#28]
![image](https://user-images.githubusercontent.com/69203685/92069149-53980280-edc6-11ea-9f92-e21bdf73e748.png)

Error in zerotomastery

**Comment by Siddharth-Selvarajan** [comment]
yes, subscribed to all courses.

**Comment by barakagb** [comment]
did other courses from zerotomastery download successfully ?

**Comment by Siddharth-Selvarajan** [comment]
all courses the same error.

**Comment by barakagb** [comment]
What is the course url on the right of your screenshot (on bin: filezilla konsole) ?

**Comment by Siddharth-Selvarajan** [comment]
https://academy.zerotomastery.io/courses/enrolled/694968

**Comment by barakagb** [comment]
> 
> 
> https://academy.zerotomastery.io/courses/enrolled/694968
so I can say that this course successfully downloaded (as it appears in the screenshot "Download completed") but also you are saying  all courses the same error . Kindly clarify.

**Comment by Siddharth-Selvarajan** [comment]
same error in windows, all courses verified.

**Comment by Siddharth-Selvarajan** [comment]
it was working for stackskills, infosec4tc

**Comment by barakagb** [comment]
Kindly share your cookies via email so I can look into  it .Thanks

**Comment by Siddharth-Selvarajan** [comment]
mail id plz

**Comment by barakagb** [comment]
You will find it here
Pip show gb-dl

**Comment by barakagb** [comment]
Hi @Siddharth-Selvarajan  kindly update gb-dl . Issue is fixed. 
Thanks

**Comment by Siddharth-Selvarajan** [comment]
Thank you so much. it's working for me.
