### ISSUE TITLE
Asks for Cookie each course

### ISSUE THREAD

**Issue by Bretthansenpc** [barakagb/gb-dl#31]
every time I try to download multiple courses using a file it won't autoload the cookie I saved instead it asks for the cookie each time it goes to a new course. Is that normal? I enter the same one each time and it continues until it's done and starts a new course. anything I can do?

**Comment by barakagb** [comment]
Hi Bret, how did you save the cookie ? and did you use the cookie auto load argument  "-a"  t?

**Comment by Bretthansenpc** [comment]
i saved the cookie using the cookie store argument -b and then yes used the auto load cookie using -a

**Comment by Bretthansenpc** [comment]
it will autoload the cookie if I don't use a file for multiple courses

**Comment by barakagb** [comment]
Let me look into it.

**Comment by Bretthansenpc** [comment]
im sorry to sound stupid but how do i upgrade? redownload from github?

**Comment by barakagb** [comment]
Run pip install gb-dl -U

**Comment by Bretthansenpc** [comment]
![gbdl 2](https://user-images.githubusercontent.com/39839076/92410669-b9072e80-f0f9-11ea-8436-f0fcec7d3789.jpg)
![gbdl](https://user-images.githubusercontent.com/39839076/92410671-b99fc500-f0f9-11ea-96e8-bc983cb4813d.jpg)

same thing when i dont use the file it works but when use the file it doesnt look for a saved cookie

**Comment by Bretthansenpc** [comment]
and when its done it asks for a cookie again

**Comment by barakagb** [comment]
Please share the course file list and cookie via email , so I dive into
it.Thank you.

**Comment by Bretthansenpc** [comment]
ok all updated and working i think haha looks like its working now thank you!
