### ISSUE TITLE
Problems with "Sanitizing file names ..."

### ISSUE THREAD

**Issue by RobinE** [barakagb/gb-dl#35]
GB-DL Downloaded a large number of folders and videos from:
stackskills.com/courses/enrolled/623434
into home directory under MacOS.  After the message on terminal "Sanitizing file names ..." things went quiet for a very long time.  Activity Monitor showed Python at 100% CPU, but nothing happening to rename the downloaded .bin files as .mp4.
After 30+ mins (ever hopeful), terminated the terminal session and used utilities to manually rename the 100+ files. They all seem to be the expected downloads.
Tried to take a quick look at the gb-dl.py file, but not familiar enough (yet) to understand what's not working in the sanitize function.
P.S. using the 1.6.7 version of gb-dl from PyPi under Python 3.8.5

**Comment by barakagb** [comment]
Noted . I have not tried the script on a mac before. But i will work on it
and revert back to you soon.

**Comment by RobinE** [comment]
No rush!  I was able to DL the files for offline viewing.  A very useful
utility

**Comment by RobinE** [comment]
I've experimented with the sanitize_file_names function.
Something along the lines of the attached function seems to work fine.
This version is useful for changing file extensions.
I've no idea why the original function seemed to hang...
[test.py.txt](https://github.com/barakagb/gb-dl/files/5441218/test.py.txt)

**Comment by barakagb** [comment]
Thanks @RobinE for the feedback . Will try and experiment  and upload a revised version.
Cheers!

**Comment by barakagb** [comment]
Hi @RobinE  , sorry for late feedback I had no access to a computer. I've done some experimenting and noted that sanitation was only done in sub-folders hence if files where in the main course folder they wouldn't be sanitized.

I made a fix and now every thing should work correctly . Kindly upgrade to v1.6.8 using pip install gb-dl -U
Cheers!

**Comment by RobinE** [comment]
Ca marche!
