### ISSUE TITLE
Source code missing

### ISSUE THREAD

**Issue by berndverst** [barakagb/gb-dl#36]
Where is your source code?

I want to inspect the code to ensure it does not send data to third party services.

**Comment by berndverst** [comment]
Ah I see - you were using youtube-dl!

Well it is safe to put the code out again.

https://www.eff.org/deeplinks/2020/11/github-reinstates-youtube-dl-after-riaas-abuse-dmca

**Comment by barakagb** [comment]
Hi there , the script doesn't send data to third parties . You can download
the script using pip install gb-dl and get a key after donating to
buymeacoff.ee/barakagb .

Thanks.

**Comment by berndverst** [comment]
@barakagb since you licensed this under the MIT license you cannot revoke the license for your old commits.

So I can just download and use this as the MIT License applies here.
https://github.com/barakagb/gb-dl/tree/7ab871aea3c41d90979bb7a8ea1a0ce6e6dd69e6

If it works I'll still buy you the coffee ;)

**Comment by barakagb** [comment]
Go ahead and try it out.

**Comment by berndverst** [comment]
FYI - I was trying to use this for some other courses on teachable, but unfortunately their layout is different and I needed to make several code changes. Got it partially working - but still seemed to have missed some DOM elements leading to videos. Too much work for the time being, and I'm back from my vacation - so no longer need offline access.

**Comment by barakagb** [comment]
> 
> 
> FYI - I was trying to use this for some other courses on teachable, but unfortunately their layout is different and I needed to make several code changes. Got it partially working - but still seemed to have missed some DOM elements leading to videos. Too much work for the time being, and I'm back from my vacation - so no longer need offline access.

@berndverst  Noted. Please can share the teachable course url so I work on the fix (even though you no longer need the offline access) it might be beneficial to other people .Thanks

**Comment by berndverst** [comment]
@barakagb https://productionmusiclive.teachable.com/

**Comment by barakagb** [comment]
Thanks let me see what I can do
