### ISSUE TITLE
Invalid course

### ISSUE THREAD

**Issue by kaajjaak** [barakagb/gb-dl#38]
I was trying to download https://iwillteachyoualanguage.teachable.com/courses/650688/
but it is saying invalid course, could you help me fix it, I wanted to try using cookies as well if that helps but I don't really understand how to do that
thanks

**Comment by barakagb** [comment]
Hi @kaajjaak , i have added the site . An easy way to get the cookie simply logon into the site with firefox (do not sign out) then run gb-dl.py -d firefox  . This willl fetch the cookie from the firefox automatically.

Please try and let me know

**Comment by kaajjaak** [comment]
okay so it started working but it is only downloading the files but not the text information, in the teachable I am using, there is also useful information under the videos in the form of text, is there a way to download that aswel, like maybe in a txt file.
Also my drive was full while downloading the files, so I deleted some files. it gave some errors but it's unclear if it continued with the files that didn't download while it was full or if it just skipped them, do you know if I will have to redo the entire download?

**Comment by kaajjaak** [comment]
also it is downloading the files as a bin instead of a mp4, is that normal?

**Comment by barakagb** [comment]
Hello,
Usually if u just redownload to the same folder it will only download
skipped files. As for the texts it usually download it misses them. As for
the bin files its normal the after downloading everything the script will
try to convert them to mp4, but you can manually change the extensionn to
mp4.Cheers!!

**Comment by barakagb** [comment]
Hi @kaajjaak . Can I close this issue ?
