### ISSUE TITLE
Is this for only the websites listed here or I want to download courses from here   https://designerup.co/

### ISSUE THREAD

**Issue by himangsusuri** [barakagb/gb-dl#4]

**Comment by himangsusuri** [comment]
https://designerup.co/

This is  also a teachable website with wistia videos

**Comment by barakagb** [comment]
Hi @himangsusuri  I have tried to modify the script for you. Please test it and kindly give feedback.
I have no account for designerup.co so i cannot test it . Good luck!
[gb-dl_v1.3.zip](https://github.com/barakagb/gb-dl/files/3828386/gb-dl_v1.3.zip)

**Comment by himangsusuri** [comment]
Sir, I can give you the account if needed but how to contact you... Many thanks for your effort

**Comment by himangsusuri** [comment]
File "<ipython-input-2-ed64b52809d1>", line 50
    elif "designerup" in self.course_url:
                                         ^
IndentationError: unindent does not match any outer indentation level error with code

**Comment by barakagb** [comment]
Hi you can find me at barakagb[a't]gmail[dot]com
Please try this script .
[gb-dl_v1.3-fixed.zip](https://github.com/barakagb/gb-dl/files/3830692/gb-dl_v1.3-fixed.zip)

**Comment by barakagb** [comment]
Hi , you can download courses from https://designerup.co/ . 
Install/Re-install the latest version .Cheers
