### ISSUE TITLE
Error find?

### ISSUE THREAD

**Issue by dem-ionz** [barakagb/gb-dl#40]
_____ ____                 _ _ 
                  / ____|  _ \               | | |
                 | |  __| |_) |  ______    __| | |
                 | | |_ |  _ <  |______|  / _` | |
                 | |__| | |_) |          | (_| | |
                  \_____|____/            \__,_|_|

           			        Version : v1.6.9.2 
                            Author  : BarakaGB
                            Visit   : https://github.com/barakagb/gb-dl
                            Donation: https://www.buymeacoffee.com/barakagb
                            Key url : https://bmc.xyz/l/gbdl
                    
    A python based utility to download courses from infosec4tc.teachable.com ,
    ehacking.net ,stackskills.com and designerup.co ...etc for personal offline 
    use.
     

    Usage: gb-dl.py [-h]   
    
Enter course url : https://stackskills.com/courses/enrolled/XXXX
Email : email@gmail.com
Password : 
Trying to Login ...
Cloudflare reCaptcha detected
Enter cookie instead: b0effff2c75f801e2a460a210211ffff
Trying cookie authentication ...
[+] Cookie authentication succeeded
[+] Logged in as Abdul Raeheh
Downloading to :/home/ionz
Collecting course information ...
[-] Error : 'NoneType' object has no attribute 'find'
➜  ~ 
That's broken. Python3

**Comment by barakagb** [comment]
Hi @dem-ionz  . This is fixed now please upgrade to 1.6.9.2 by running pip install gb-dl -U.Thanks

**Comment by barakagb** [comment]
@dem-ionz  can I close this issue ?
