### ISSUE TITLE
Invalid Key

### ISSUE THREAD

**Issue by tgreenev** [barakagb/gb-dl#43]
Hello, 

I purchased a key back in June 2020, and now that I am trying to use it again to get more courses, I am getting this error. What's the reason for this?

**Comment by barakagb** [comment]
@tgreenev  please dm me your key and I check.Thanks.
info@gb-dl.cf

**Comment by barakagb** [comment]
@tgreenev Sorry for the inconvenience .This has been resolved .Kindly try again.
Cheers!!

**Comment by tgreenev** [comment]
This is fixed. Thanks!
