### ISSUE TITLE
Cannot launch program

### ISSUE THREAD

**Issue by baggot4** [barakagb/gb-dl#44]
https://gyazo.com/b454cd56db6346c1e384b1051b16ecc8

I opened the cmd in the file path, ran pip install gb-dl.py then ran py gb-dl.py
and this is what shows up. What and i doing wrong?

**Comment by baggot4** [comment]
figured it out, but now my  key that i bought in 05/25/2020 isnt working

**Comment by barakagb** [comment]
Dm the keys at info at gb-dl dot cf

**Comment by baggot4** [comment]
> gb-dl

Can you re-phrase the question?

**Comment by barakagb** [comment]
@baggot4  try now.

**Comment by baggot4** [comment]
it worked but how do i load urls from a file when i run gb-dl.py -f it says
this "gb-dl: error: argument -f/--file: expected one argument"

**Comment by barakagb** [comment]
have you specified the file name with the urls ?
e.g gb-dl.py -f url.txt

**Comment by baggot4** [comment]
yes i did, "gb-dl.py -f url.txt" same error

**Comment by barakagb** [comment]
can you share a screen shot

**Comment by baggot4** [comment]
Here is the link (sorry for the name, my friend gave me a pays.host access
for free so thats all i have to screenshot)
https://i-hate.transgenders.gay/wBGV6PQs

**Comment by barakagb** [comment]
![Capture](https://user-images.githubusercontent.com/30619781/119942065-1437c480-bf9a-11eb-8e75-561db51636e8.PNG)

@baggot4  please check that you are pointing to an existing file .
I have tried it and it works for me.

**Comment by baggot4** [comment]
I got it to work, needed the whole path. ANother question, how do i change
the download location, it is currently downloading on my c drive i need it
on my d drive

**Comment by barakagb** [comment]
The script downloads courses to the current working directory . So if you want to download in D:\  cd D:\  then run gb-dl from there.

**Comment by baggot4** [comment]
i tried that, now i am in the correct folder when i try to give a path to
the url.txt it says "not  a valid path d:\\gb-dl\\urls.txt"          when
the command i entered was              "gb-dl.py -f d:\gb-dl\urls.txt"

**Comment by barakagb** [comment]
@baggot4 . I have tried and it works for me (see image). Could you share a screen shot.
![Screenshot_2021-05-31_12-44-50](https://user-images.githubusercontent.com/30619781/120174451-c925e780-c20d-11eb-94a7-bd1b87cee3a0.png)

**Comment by barakagb** [comment]
@baggot4  is there any update on this ?
