### ISSUE TITLE
Can't Run Program

### ISSUE THREAD

**Issue by c0depanda** [barakagb/gb-dl#45]
Not sure what i am doing wrong but i can't seem to get this up and running. 

I have installed using pip install gb-dl

That's done but anytime i run 

`gb-dl.py` command not found: gb-dl. So not sure what else i need to do to get it working.

**Comment by barakagb** [comment]
You need to check your environment variables.
Is python in your env variables?
What Os are you using?

**Comment by barakagb** [comment]
@c0depanda and feedback on the above ?
