### ISSUE TITLE
reCaptcha Cookie question

### ISSUE THREAD

**Issue by 3l3phant** [barakagb/gb-dl#46]
When trying to launch and authenticate into StackSkills I'm getting the message that it's detecting the Cloudflare reCaptcha. Which cookie content should I provide? From the session ID? Also, is there a way to configure where the files are downloaded? If not (which is not a problem :)) what is the default location? Thank you!

**UPDATE**: I decided to use the -d and grabbed the .sqlite cookie file from firefox and it worked. Still curious about the ability to set a download directory.

**Comment by barakagb** [comment]
Hi,
Use the session_id for cookie.The script downloads files in the current
working folder.So simply navigate to where you want to download the files
and run gb-dl.
Thanks

**Comment by barakagb** [comment]
@3l3phant , I will add the feature in the next release. Thanks
