### ISSUE TITLE
No key after purchase

### ISSUE THREAD

**Issue by scottarnold** [barakagb/gb-dl#51]
I purchased a license and never received a key to my email. I _did_ get an email, but it only contained a link to the README. (I checked spam to no avail 😢).

Please advise, thanks!

**Comment by scottarnold** [comment]
The email came ~45min after purchase. Thank you!

**Comment by barakagb** [comment]
sorry for the the key delay. It usually takes like a minute or so am looking on to it to see what was the problem.
