### ISSUE TITLE
Invalid course URL error for "https://serpentine-studies.teachable.com/courses"

### ISSUE THREAD

**Issue by jin-ds** [barakagb/gb-dl#54]
Hi there,

I'm also getting an error for a course on URL:

https://serpentine-studies.teachable.com/courses

Thanks!

**Comment by barakagb** [comment]
Fixed.

**Comment by jin-ds** [comment]
Thanks for taking a look!

I'm getting this error now:

`[-] Could not contact remote server.`

Let me know if more info is needed!

**Comment by jin-ds** [comment]
That did the trick, thanks so much!

I would, however, suggest adding in the documentation to first use that command, then log into the course with Firefox and then run the `gb-dl.py -d firefox` command, as that seems to be doing the trick (after the invalid-course-url error was resolved). Thanks!

Feel free to close this one out!
