### ISSUE TITLE
Invalid course URL error for "https://navadance.teachable.com/courses"

### ISSUE THREAD

**Issue by jin-ds** [barakagb/gb-dl#55]
Hi there,

I have the invalid course URL error for the course on link:

https://navadance.teachable.com/courses/enrolled/834057

Thanks!

**Comment by barakagb** [comment]
fixed.

**Comment by jin-ds** [comment]
Thanks for taking a look!

I'm getting this error now:

`[-] Could not contact remote server.`

Let me know if more info is needed!

**Comment by barakagb** [comment]
kindly upgrade gb-dl , run pip install gb-dl -U

**Comment by jin-ds** [comment]
That did the trick, thanks so much!

I would, however, suggest adding in the documentation to first use that command, then log into the course with Firefox and then run the `gb-dl.py -d firefox` command, as that seems to be doing the trick (after the invalid-course-url error was resolved). Thanks!

Feel free to close this one out!
