### ISSUE TITLE
No key after purchase

### ISSUE THREAD

**Issue by ICDeadPpl** [barakagb/gb-dl#58]
How long will it take to get the key? It's been 10 minutes, and I only got an email with a link to a file (gb-dl_key_instruction.md) which didn't contain any key, just the same instructions as on the Github page.
I have nothing in my span folder either.

**Comment by ICDeadPpl** [comment]
Almost 8 hours later, no key. Going to start a refund process.
Nice thing you've got going here...

**Comment by barakagb** [comment]
Hi @ICDeadPpl sorry for the inconviniece . It seems there was a problem with emailiing the keys I have to manually generate and send you one. Kindly check your inbox in a few minutes.Thanks

**Comment by barakagb** [comment]
@ICDeadPpl  Kindly note that the key has already been sent to your email. 
Once again my apologies for the inconvenience. This is also due time difference, would have sent it earlier.

Thanks
