### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by LienCF** [barakagb/gb-dl#59]
When running gb-dl.py to download, it shows the following message and not able to process.

HTTPSConnectionPool(host='venvgb.cf', port=443): Max retries exceeded with url: /l/ (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Service Unavailable')))

**Comment by barakagb** [comment]
Working on it ...

**Comment by barakagb** [comment]
@LienCF  this has been fixed. Kindly confirm.

**Comment by LienCF** [comment]
@barakagb Thanks. I can confirm that it works again.
