### ISSUE TITLE
Connection failed

### ISSUE THREAD

**Issue by nbctcp** [barakagb/gb-dl#6]
ERROR:
Password :
Trying to Login ...
[-] Connection failed.Please check your internet connection and try again!
 value

I am using 2nd January git clone.
That's the error I encounter,
Ping to internet no problem
Login to webpage no problem
I think that because it protected by Cloudflare
tq

**Comment by barakagb** [comment]
Hi @nbctcp  kindly share more details e.g course url and screenshot  . You can send me the details in my email(found when running the script)  if you are not comfortable sharing here.Thanks

**Comment by barakagb** [comment]
Hi Kindly uninstall and reinstall the script using pip install gb-dl.
This is resolved .Thanks
Kindly consider donating

https://www.buymeacoffee.com/barakagb
 https://www.ko-fi.com/barakagb
