### ISSUE TITLE
Invalid Course URL For https://growyouragency.teachable.com/courses/enrolled/632756 

### ISSUE THREAD

**Issue by lxxiv** [barakagb/gb-dl#60]

**Comment by barakagb** [comment]
@lxxiv fixed. Please try again.

**Comment by lxxiv** [comment]
I get this issue now. Any idea on how to solve it
<img width="567" alt="Screen Shot 2021-12-25 at 8 29 59 AM" src="https://user-images.githubusercontent.com/60582320/147379979-22ec82d0-c6de-424f-b2e6-3cefe6d248d2.png">
?

**Comment by barakagb** [comment]
What os are you using?

**Comment by lxxiv** [comment]
Mac OS

**Comment by barakagb** [comment]
You can try entering the cookies manually

**Comment by lxxiv** [comment]
How do I do that?

**Comment by barakagb** [comment]
You can try entering the cookies manually
What version of gb-dl are running ? Please share the full screenshot ommitting your private info.
Thanks

**Comment by barakagb** [comment]
@lxxiv any feedback on this ?
