### ISSUE TITLE
Can not download courses that have '/' in the course name

### ISSUE THREAD

**Issue by LienCF** [barakagb/gb-dl#61]
I'm downloading course with ubuntu os. The '/' is not allowed in filename or path name, so it's not able to create folder for this course.

Downloading https://stackskills.com/courses/enrolled/86723
 ...
Trying to Login ...
Cloudflare reCaptcha detected
Trying cookie authentication ...
cp: cannot stat '/home/liencf/.mozilla/firefox/*.default*/sessionstore-backups/*.jsonlz4': No such file or directory
[+] Cookie authentication succeeded
Getting sections
[+] Logged in successful
Downloading to :/home/liencf/gdrive/mount_rclone1/MultiMedia/Courses
Collecting course information ...

Course name : Outsource your idea | Launch your business for 1/4 the price
[-] Error : [Errno 2] No such file or directory: 'Outsource your idea  Launch your business for 1/4 the price'

**Comment by barakagb** [comment]
@LienCF I need cookies to the course so I can try to fix it. I have tried some courses with invalid folder name characters and seems to work fine. Please share the cookies privately.Thanks

**Comment by LienCF** [comment]
@barakagb Are you testing on Windows or Linux? What is the name of the folder you are trying to reproduce the issue in? And what's the folder created?

If you try to create a folder named "Outsource your idea Launch your business for 1/4 the price" in Ubuntu or any other linux system, you should be able to reproduce the problem.

**Comment by barakagb** [comment]
I faced a similar problem wayback and implemented the solution that seems
not to be working in your case.Thats why I requested for cookies. I will be
harder for me to fix if I cant replicate the problem.

**Comment by LienCF** [comment]
@barakagb Thanks. How do I send private message to you?

**Comment by LienCF** [comment]
@barakagb The cookie is.
"https://stackskills.com": "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJ1c2VyIiwiaWF0IjoxNjM4MDYwODQ0LCJqdGkiOiJjYzFiYWIwOC05NjE1LTRiNDMtYjk3Yi1jZmY3MTI5ZDJkMTIiLCJpc3MiOiJza19nOGx6NnJiNiIsInN1YiI6ImQ1NzA3NWI4LTY5NmYtNGRmZC1iMGZhLWM3Nzg3MTYxMjEyOCJ9.1taL5dVam0i2vJ-05WaU0wNyLKwYXPsKuAWMsBtTm-Q"

**Comment by barakagb** [comment]
Yes, I have received the cookies. Let me work on a fix

**Comment by barakagb** [comment]
@LienCF you sent the wrong cookie, the authentication failed . However, I think I have a solution.
Upgrade gb-dl wit pip3 install gb-dl -U

**Comment by LienCF** [comment]
@barakagb Yes. Updated gb-dl.py and it worked.
And strangely enough, the cookieis working for me. I just tried this course and I can log in successfully with a cookie.
However, there is another problem with this course, which is that it is not available for download.

Downloading https://stackskills.com/courses/enrolled/69490
 ...
Trying to Login ...
Cloudflare reCaptcha detected
Trying cookie authentication ...
cp: cannot stat '/home/liencf/.mozilla/firefox/*.default*/sessionstore-backups/*.jsonlz4': No such file or directory
[+] Cookie authentication succeeded
Getting sections
[+] Logged in successful
Downloading to :/home/liencf/gdrive/mount_rclone1/MultiMedia/Courses
Collecting course information ...
[-] Error : 'NoneType' object has no attribute 'find'

**Comment by barakagb** [comment]
I need also cookies to this, share the _session_id and sk_access_* values .

**Comment by LienCF** [comment]
@barakagb The session_id is 7bec31f144739e64282113488421e20c and the sk_g8lz6rb6_access is eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJ1c2VyIiwiaWF0IjoxNjQyMDM2MTg5LCJqdGkiOiJkMmFhNWQ2OS0wZWUyLTQ3NTMtODNhOS00OWQ2ZGYwNjViNmEiLCJpc3MiOiJza19nOGx6NnJiNiIsInN1YiI6ImQ1NzA3NWI4LTY5NmYtNGRmZC1iMGZhLWM3Nzg3MTYxMjEyOCJ9.D0PLb0ioSARNJOLUHxzn8692hcBEQSmDX636veWi33o

**Comment by LienCF** [comment]
Hi @barakagb , did you received the new cookie? And how about the issue?

**Comment by barakagb** [comment]
No, I did not. You can share via email.

**Comment by LienCF** [comment]
@barakagb The _session_id is 7bec31f144739e64282113488421e20c
The sk_g8lz6rb6_access is eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJ1c2VyIiwiaWF0IjoxNjQyNTExMzA3LCJqdGkiOiJlZTRmZWJjNC0yYmFmLTRjNGItYTI3MC03MWRiNTQ2Njc2OTQiLCJpc3MiOiJza19nOGx6NnJiNiIsInN1YiI6ImQ1NzA3NWI4LTY5NmYtNGRmZC1iMGZhLWM3Nzg3MTYxMjEyOCJ9.KEJHe2dTZ6YmHQbdi8bqNQthS5PJvV7ibFM4juvA2ak

**Comment by barakagb** [comment]
Recived

**Comment by barakagb** [comment]
Doesnt seem to work

**Comment by LienCF** [comment]
It's weird. I just copy the cookie value from my firefox. Let me logout and login and give you the cookie again.

**Comment by LienCF** [comment]
The _session_id is 7bec31f144739e64282113488421e20c
The sk_g8lz6rb6_access is eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJ1c2VyIiwiaWF0IjoxNjQyNTEyNzA4LCJqdGkiOiI2ZDkwYWRkZi1kMWFjLTQxYjctOTUzNi1iN2YzZjFiNDcxMGMiLCJpc3MiOiJza19nOGx6NnJiNiIsInN1YiI6Ijc5ZDViZDdmLTA4YmUtNDc4NC04MjViLWI2MTVkNjdiMTU2MiJ9.a1yBL9SQnDkt1feH70aDeULE-OIENLCxgo3YuXO9zdc

**Comment by barakagb** [comment]
Yes...let me work on a fix!

**Comment by barakagb** [comment]
Fixed! upgrade to the latest version.

**Comment by LienCF** [comment]
@barakagb After upgrade gb-dl, I can not login with cookie anymore.
What should I input when prompt to enter cookie ? "Enter cookie instead:"
Is it the value of "sk_g8lz6rb6_access" ?

**Comment by barakagb** [comment]
Yes , unfortunately there was a problem with authentication in the latest
version.Kindly downgrade

**Comment by barakagb** [comment]
Please upgrade to the latest version.Thanks

**Comment by LienCF** [comment]
@barakagb Thanks. the new version works.
I tried the https://stackskills.com/courses/enrolled/69490 course.

The new script can download courses but not able to get the course name.

`Enter course url > https://stackskills.com/courses/enrolled/69490
[i] Browser: firefox
[i] Trying cookie authentication ...
[+] Cookie authentication succeeded
[+] Cookie stored to file
[i] Getting sections
[+] Logged in successful
Downloading to : gb-dl
Collecting course information ...
[-] Failed to get course name, setting course name to Unknown course.

Course name : Unknown course
[i] Getting course sections ...`

**Comment by barakagb** [comment]
Yes ,that is noted .For some courses it can fail to get the course name.
