### ISSUE TITLE
[-] Invalid course URL.

### ISSUE THREAD

**Issue by m1zr** [barakagb/gb-dl#62]
Hi, 

Trying to get this course to have it on my laptop but I get invalid URL. It's a teachable course.
URL: https://pro.academind.com/courses/enrolled/767953

**Comment by barakagb** [comment]
Hi @m1zr , school added . PLease try now.

**Comment by m1zr** [comment]
> Hi @m1zr , school added . PLease try now.

It can't log in, asks for cookie and tried to copy it from inspector as JSON, as value etc etc. but nothing works. How does the script expect the cookie? Can you please send instructions?

**Comment by barakagb** [comment]
The easiest way to get the cookies is  login to the course in firefox and then  run gb-dl.py -d firefox 
the script will automatically load the cookies.You can find more help by runing gb-dl.py -h.

**Comment by m1zr** [comment]
Thank you, that worked.

Just for clarification:
1. I have logged in using Firefox. 
2. Opened up powershell and typed in `gb-dl.py`, it opened up the script in VS code.
3. I ran py `gb-dl.py -d firefox` as per your instruction.
4. It simply asks for a course URL and cookie authentication is done automatically.

Thanks for support.
