### ISSUE TITLE
Paid, Didn't get licence

### ISSUE THREAD

**Issue by AppreciateIT** [barakagb/gb-dl#65]
Hey, I paid but didn't receive licence?  It was not in the Access link file, and is not in my email or spam. :-(  
Hope you are well.
Please send and I'll remove this issue. Cheers

**Comment by barakagb** [comment]
Hi , apologizes for the incovinience .Let me look into it and get back to
you. Usually you should get the key almost immediately.

**Comment by AppreciateIT** [comment]
No problem.  Sorry I was in such a hurry.  All is well.  Cheers.
