### ISSUE TITLE
Connection timed out to venvgb.cf

### ISSUE THREAD

**Issue by LienCF** [barakagb/gb-dl#66]
Enter course url > https://stackskills.com/courses/enrolled/1058255
[i] Trying cookie authentication ...
HTTPSConnectionPool(host='venvgb.cf', port=443): Max retries exceeded with url: /l/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10563b130>: Failed to establish a new connection: [Errno 60] Operation timed out'))
[-] Error : Connection failed . Check your internet connection and try again!

**Comment by barakagb** [comment]
Noted. Working on it

**Comment by barakagb** [comment]
Please upgrade gb-dl by running 
pip install gb-dl -U

**Comment by LienCF** [comment]
Thank you. It is working.
