### ISSUE TITLE
"Enter Cookie Instead" 

### ISSUE THREAD

**Issue by trissy69** [barakagb/gb-dl#67]
When using gb-dl ; I enter the email and password when prompted which brings the following response:

[i] Trying to Login ... 4459 [i] Cloudflare reCaptcha detected Enter cookie instead >

How do I enter the cookie? I cant find any resources regarding this. Please help.

I have downloaded the cookie on a file. How do I "enter the cookie" ?? Nothing I try seems to work.

**Comment by barakagb** [comment]
The easiest way is to login to the site on firefox then, simply run gb-dl.py -d firefox it will load cookies automatically.
