### ISSUE TITLE
not working on stackskills.com

### ISSUE THREAD

**Issue by andrewiassur** [barakagb/gb-dl#7]
Enter course url : url
Email : email
Password : 
Trying to Login ...
[-] Connection failed.Please check your internet connection and try again!
 
init_poolmanager() got an unexpected keyword argument 'ssl_context'

i have an internet connection email address password and url are correct. does this have to do with the ddos protection for cloud flare?

**Comment by barakagb** [comment]
Hi Andrew , I am working on a fix . will share soon.Thanks

**Comment by andrewiassur** [comment]
thank you very much

**Comment by barakagb** [comment]
Hi Andrew , the issue has been fixed kindly goto https://bmc.xyz/l/gbdl to download the latest version.Thanks
