### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by tdsprouse** [barakagb/gb-dl#8]
Program starts, prompts for Course url, then Email, and tehn Course url again.  no matter what is entered, it dumps out back to cmmd prompt

![image](https://user-images.githubusercontent.com/24418269/72293132-db0ae880-3620-11ea-881d-8f75980403e3.png)

(on Windows 10)

**Comment by barakagb** [comment]
Working on a fix ...will resolve soon

**Comment by tdsprouse** [comment]
Thanks!  I appreciate it!

**Comment by barakagb** [comment]
Hi @tdsprouse , the issue has been fixed .Kindly go to https://bmc.xyz/l/gbdl to download a latest version.Thanks.   `https://bmc.xyz/l/gbdl `

**Comment by tdsprouse** [comment]
Thanks, got the file, ran it, it opened a new window, looked like it was going to work...  It got to 'Trying to login' and then teh window just closed.

**Comment by barakagb** [comment]
are you using windows or linux ??

**Comment by tdsprouse** [comment]
windows 10, I ran the .exe you had posted.

**Comment by barakagb** [comment]
open cmd then run the script

**Comment by tdsprouse** [comment]
ah, more info this time... 

![image](https://user-images.githubusercontent.com/24418269/72379703-f38f0780-36e1-11ea-97f6-1c33a2f66178.png)

**Comment by barakagb** [comment]
![Screenshot (98)](https://user-images.githubusercontent.com/30619781/72380255-0cb9a780-3726-11ea-98d4-908236cc67ff.png)

**Comment by tdsprouse** [comment]
I will try from a different location this evening.

**Comment by barakagb** [comment]
okay ..kindly provide feedback .Thanks

**Comment by barakagb** [comment]
use the v1.4

**Comment by tdsprouse** [comment]
Appears to be working now.  is downloading first course, though will
probably take a good long time to get it all.  :)

Thanks so much!
